---

- name: customize docker-compose.override.yml
  template:
    src: docker-compose.override.yml.j2
    dest: '{{ project_path }}/deployment/docker-compose.override.yml'
    owner: '{{ remote_user }}'
    group: '{{ remote_group }}'
    mode: "u=rw,g=rw,o=r"
  tags:
    - development

- name: customize Realtime REST API env
  template:
    src: realtime_rest_api/realtime-rest.env.j2
    dest: '{{ project_path }}/deployment/docker-realtime/{{ item }}'
    owner: '{{ remote_user }}'
    group: '{{ remote_group }}'
    mode: "u=rw,g=rw,o=r"
  with_items:
    - 'realtime-rest.env'
