sudo: required

language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

services:
  - docker

branches:
  only:
    - develop

before_install:
  - sudo apt-get -y update
  - sudo apt-get -y install libssl-dev
  - sudo pip install -r REQUIREMENTS-TRAVIS.txt

install:
  # build current docker image
  - cd deployment
  - cp ansible/development/group_vars/all.travis.yml ansible/development/group_vars/all.yml
  - make setup-ansible ANSIBLE_ARGS="--extra-vars='ansible_sudo_pass=\"\"' --extra-vars='pycharm_version=\"\"' --skip-tags=development"
  - make build
  - make up
  - make status
  - cd ../

script:
  - flake8 src
  # Check realtime settings
  - cd deployment
  - make coverage-tests
  - cd ../

after_script:
  # Clean up
  - make down

after_success:
  - cd src/realtime
  - codecov
  - cd ../../
